/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClasesyFormas;

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Maza
 */
public class AdminA extends javax.swing.JFrame {

    PreparedStatement ps;
    ResultSet rs, rs1;
    Conexion C = new Conexion();

    /**
     * Creates new form frmMiCRUD
     */
    public AdminA() {
        initComponents();
        setLocationRelativeTo(null);
        mostrarDatos();
        lblMensaje.setText("Constructor sin parametros");
        this.CodigoTXT.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblMensaje = new javax.swing.JLabel();
        lblNOMBRE = new javax.swing.JLabel();
        txtNOMBREALUM = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtAPELLIDO = new javax.swing.JTextField();
        lblCURSO = new javax.swing.JLabel();
        txtCURSO = new javax.swing.JTextField();
        cmdGUARDAR = new javax.swing.JButton();
        cmdEDITAR = new javax.swing.JButton();
        cmdELIMINAR = new javax.swing.JButton();
        cmdNUEVO = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablaAlumnos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtCALIFICACION = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CodigoTXT = new javax.swing.JTextField();
        cmdEDITAR1 = new javax.swing.JButton();
        cmdEDITAR2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 24, 57));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mantenimiento de Alumnos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        lblMensaje.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 255, 255));
        lblMensaje.setText("PRUEBA CONSTRUCTOR");

        lblNOMBRE.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        lblNOMBRE.setForeground(new java.awt.Color(255, 255, 255));
        lblNOMBRE.setText("Nombre del Alumno");

        txtNOMBREALUM.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txtNOMBREALUM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNOMBREALUMKeyPressed(evt);
            }
        });

        lblApellido.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(255, 255, 255));
        lblApellido.setText("Apellidos del Alumno:");

        txtAPELLIDO.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txtAPELLIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAPELLIDOActionPerformed(evt);
            }
        });
        txtAPELLIDO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAPELLIDOKeyPressed(evt);
            }
        });

        lblCURSO.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        lblCURSO.setForeground(new java.awt.Color(255, 255, 255));
        lblCURSO.setText("Curso:");

        txtCURSO.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        txtCURSO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCURSOKeyPressed(evt);
            }
        });

        cmdGUARDAR.setBackground(new java.awt.Color(255, 255, 255));
        cmdGUARDAR.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cmdGUARDAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/i.png"))); // NOI18N
        cmdGUARDAR.setText("GUARDAR");
        cmdGUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGUARDARActionPerformed(evt);
            }
        });

        cmdEDITAR.setBackground(new java.awt.Color(255, 255, 255));
        cmdEDITAR.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cmdEDITAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/a.png"))); // NOI18N
        cmdEDITAR.setText("EDITAR");
        cmdEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEDITARActionPerformed(evt);
            }
        });

        cmdELIMINAR.setBackground(new java.awt.Color(255, 255, 255));
        cmdELIMINAR.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cmdELIMINAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/e.png"))); // NOI18N
        cmdELIMINAR.setText("ELIMINAR");
        cmdELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdELIMINARActionPerformed(evt);
            }
        });

        cmdNUEVO.setBackground(new java.awt.Color(255, 255, 255));
        cmdNUEVO.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cmdNUEVO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Limpiar.png"))); // NOI18N
        cmdNUEVO.setText("LIMPIAR");
        cmdNUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNUEVOActionPerformed(evt);
            }
        });

        jtablaAlumnos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), java.awt.Color.black, java.awt.Color.black));
        jtablaAlumnos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtablaAlumnos.setAlignmentX(1.0F);
        jtablaAlumnos.setAlignmentY(1.0F);
        jtablaAlumnos.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jtablaAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtablaAlumnos);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Calificacion");

        txtCALIFICACION.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo del Alumno");

        CodigoTXT.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        CodigoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoTXTActionPerformed(evt);
            }
        });
        CodigoTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CodigoTXTKeyPressed(evt);
            }
        });

        cmdEDITAR1.setBackground(new java.awt.Color(255, 255, 255));
        cmdEDITAR1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cmdEDITAR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/b.png"))); // NOI18N
        cmdEDITAR1.setText("BUSCAR");
        cmdEDITAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEDITAR1ActionPerformed(evt);
            }
        });

        cmdEDITAR2.setBackground(new java.awt.Color(255, 255, 255));
        cmdEDITAR2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cmdEDITAR2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/s.png"))); // NOI18N
        cmdEDITAR2.setText("Regresar");
        cmdEDITAR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEDITAR2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(cmdEDITAR1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmdGUARDAR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmdEDITAR))
                            .addComponent(cmdNUEVO, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 593, Short.MAX_VALUE)
                        .addComponent(cmdEDITAR2)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(cmdELIMINAR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNOMBREALUM, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(lblCURSO, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblApellido)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(128, 128, 128)
                                    .addComponent(CodigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtAPELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCURSO, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCALIFICACION, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(cmdEDITAR1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 413, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdGUARDAR)
                    .addComponent(cmdEDITAR))
                .addGap(43, 43, 43)
                .addComponent(cmdELIMINAR)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdEDITAR2)
                    .addComponent(cmdNUEVO))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblMensaje))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(5, 5, 5)
                            .addComponent(CodigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblNOMBRE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNOMBREALUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(lblApellido)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtAPELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(lblCURSO)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCURSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCALIFICACION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(61, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAPELLIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAPELLIDOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAPELLIDOActionPerformed

    private void cmdGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGUARDARActionPerformed
        // TODO add your handling code here:
        insertarDatos();
        mostrarDatos();
    }//GEN-LAST:event_cmdGUARDARActionPerformed

    public void insertarDatos() {
        try {

            ps = C.getConection().prepareStatement("INSERT INTO alumnos (Id_A,Nombre,Apellido,Materia,Calificacion) VALUES(?,?,?,?,?) ");
            ps.setInt(1, Integer.parseInt(CodigoTXT.getText()));
            ps.setString(2, txtNOMBREALUM.getText());
            ps.setString(3, txtAPELLIDO.getText());
            ps.setString(4, txtCURSO.getText());
            ps.setString(5, txtCALIFICACION.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null, "Registro Exitoso");
            limpiarDatos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Registrar");
            limpiarDatos();
        }
    }
    private void cmdELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdELIMINARActionPerformed
        try {
            ps = C.getConection().prepareStatement("DELETE FROM alumnos WHERE Id_A= ? ");
            ps.setInt(1, Integer.parseInt(CodigoTXT.getText()));
            //int filaSelect = jtablaAlumnos.getSelectedRow();
            ps.execute();
            JOptionPane.showMessageDialog(null, "Registro eliminar Exitosamente");
            limpiarDatos();
            mostrarDatos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Eliminar");
            limpiarDatos();
        }
    }//GEN-LAST:event_cmdELIMINARActionPerformed
    public void eliminar(String id) {

    }
    private void cmdEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEDITARActionPerformed
        // TODO add your handling code here: 
        EDITAR();
        mostrarDatos();

    }//GEN-LAST:event_cmdEDITARActionPerformed
    public void EDITAR() {
        try {
            ps = C.getConection().prepareStatement("UPDATE alumnos SET Id_A=?,Nombre=?,Apellido=?,Materia=?,Calificacion=? WHERE Id_A= ?  ");
            ps.setInt(1, Integer.parseInt(CodigoTXT.getText()));
            ps.setString(2, txtNOMBREALUM.getText());
            ps.setString(3, txtAPELLIDO.getText());
            ps.setString(4, txtCURSO.getText());
            ps.setString(5, txtCALIFICACION.getText());
            ps.setInt(6, Integer.parseInt(CodigoTXT.getText()));
            ps.execute();

            JOptionPane.showMessageDialog(null, "Registro Actualizado Exitosamente");
            limpiarDatos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Editar");
            limpiarDatos();
        }
    }
    
    
    
    
    
    
    private void cmdNUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNUEVOActionPerformed
        // TODO add your handling code here:
        limpiarDatos();
    }//GEN-LAST:event_cmdNUEVOActionPerformed

    private void jtablaAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaAlumnosMouseClicked
        // TODO add your handling code here:
        int filaSelect = jtablaAlumnos.rowAtPoint(evt.getPoint());
        String id = (String) jtablaAlumnos.getValueAt(filaSelect, 0);
        CodigoTXT.setText(id);
        txtNOMBREALUM.setText(jtablaAlumnos.getValueAt(filaSelect, 1).toString());
        txtAPELLIDO.setText(jtablaAlumnos.getValueAt(filaSelect, 2).toString());
        txtCURSO.setText(jtablaAlumnos.getValueAt(filaSelect, 3).toString());
        txtCALIFICACION.setText(jtablaAlumnos.getValueAt(filaSelect, 4).toString());
    }//GEN-LAST:event_jtablaAlumnosMouseClicked

    private void CodigoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoTXTActionPerformed

    private void cmdEDITAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEDITAR1ActionPerformed
        try {
            ps = C.getConection().prepareStatement("SELECT * FROM alumnos WHERE Id_A = ?  ");
            ps.setInt(1, Integer.parseInt(CodigoTXT.getText()));
            rs = ps.executeQuery();
             if(rs.next()){
                CodigoTXT.setText(rs.getString("Id_A")) ;
                txtNOMBREALUM.setText(rs.getString("Nombre")) ;
                txtAPELLIDO.setText(rs.getString("Apellido")) ;
                txtCURSO.setText(rs.getString("Materia")) ;
                txtCALIFICACION.setText(rs.getString("Calificacion")) ;  
               
                mostrarDatosB();
            }else{
            JOptionPane.showMessageDialog(null, "No existe Codigo del Alumno");
            limpiarDatos();
            mostrarDatos();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar Datos");
            limpiarDatos();
        }
    }//GEN-LAST:event_cmdEDITAR1ActionPerformed

    private void CodigoTXTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoTXTKeyPressed
        char t = evt.getKeyChar();
        if (t == KeyEvent.VK_ENTER) {
            this.txtNOMBREALUM.requestFocus();
        }
    }//GEN-LAST:event_CodigoTXTKeyPressed

    private void txtNOMBREALUMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNOMBREALUMKeyPressed
        char t = evt.getKeyChar();
        if (t == KeyEvent.VK_ENTER) {
            this.txtAPELLIDO.requestFocus();
        }
    }//GEN-LAST:event_txtNOMBREALUMKeyPressed

    private void txtAPELLIDOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAPELLIDOKeyPressed
        char t = evt.getKeyChar();
        if (t == KeyEvent.VK_ENTER) {
            this.txtCURSO.requestFocus();
        }
    }//GEN-LAST:event_txtAPELLIDOKeyPressed

    private void txtCURSOKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCURSOKeyPressed
        char t = evt.getKeyChar();
        if (t == KeyEvent.VK_ENTER) {
            this.txtCALIFICACION.requestFocus();
        }
    }//GEN-LAST:event_txtCURSOKeyPressed

    private void cmdEDITAR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEDITAR2ActionPerformed
        Menu1 A = new Menu1();
                        A.setVisible(true);
                        this.dispose();  
    }//GEN-LAST:event_cmdEDITAR2ActionPerformed

    public void limpiarDatos() {
        txtAPELLIDO.setText("");
        txtNOMBREALUM.setText("");
        txtCALIFICACION.setText("");
        txtCURSO.setText("");
        CodigoTXT.setText("");
mostrarDatos();
    }

    public void mostrarDatos() {

        String[] titulos = {"Codigo", "Nombre", "Apellido", "Materia", "Calificacion"};

        String[] registros = new String[7];

        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        String sql = "select * from  alumnos";

        try {
            ps = C.getConection().prepareStatement("SELECT * FROM alumnos");

            rs = ps.executeQuery();

            while (rs.next()) {

                registros[0] = rs.getString("Id_A");
                registros[1] = rs.getString(("Nombre"));
                registros[2] = rs.getString("Apellido");
                registros[3] = rs.getString("Materia");
                registros[4] = rs.getString("Calificacion");

                modelo.addRow(registros);
            }

            jtablaAlumnos.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar Datos" + e.getMessage());
        }

    }

    public void mostrarDatosB() {

        String[] titulos = {"Codigo", "Nombre", "Apellido", "Materia", "Calificacion"};

        String[] registros = new String[7];

        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        String sql = "select * from  alumnos";

        try {
            ps = C.getConection().prepareStatement("SELECT * FROM alumnos WHERE Id_A= ?  ");
            ps.setInt(1, Integer.parseInt(CodigoTXT.getText()));
            rs = ps.executeQuery();

            while (rs.next()) {

                registros[0] = rs.getString("Id_A");
                registros[1] = rs.getString(("Nombre"));
                registros[2] = rs.getString("Apellido");
                registros[3] = rs.getString("Materia");
                registros[4] = rs.getString("Calificacion");

                modelo.addRow(registros);
            }

            jtablaAlumnos.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al mostrar Datos" + e.getMessage());
        }

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodigoTXT;
    private javax.swing.JButton cmdEDITAR;
    private javax.swing.JButton cmdEDITAR1;
    private javax.swing.JButton cmdEDITAR2;
    private javax.swing.JButton cmdELIMINAR;
    private javax.swing.JButton cmdGUARDAR;
    private javax.swing.JButton cmdNUEVO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable jtablaAlumnos;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCURSO;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNOMBRE;
    private javax.swing.JTextField txtAPELLIDO;
    private javax.swing.JTextField txtCALIFICACION;
    private javax.swing.JTextField txtCURSO;
    private javax.swing.JTextField txtNOMBREALUM;
    // End of variables declaration//GEN-END:variables

    private void eliminar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
